<a href="https://colab.research.google.com/github/sukhyun1017/pytorch-study/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [4]:
model = nn.Linear(1,1)
#model = nn.Linear(input_dim, output_dim)
#cost = F.mse_loss(prediction, y_train)

In [6]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [7]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [8]:
# 전체 훈련 데이터에 대해 경사 하강법을 1,000회 반복
nb_epochs = 1000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/1000 Cost: 13.103541
Epoch  100/1000 Cost: 0.002791
Epoch  200/1000 Cost: 0.001724
Epoch  300/1000 Cost: 0.001066
Epoch  400/1000 Cost: 0.000658
Epoch  500/1000 Cost: 0.000407
Epoch  600/1000 Cost: 0.000251
Epoch  700/1000 Cost: 0.000155
Epoch  800/1000 Cost: 0.000096
Epoch  900/1000 Cost: 0.000059
Epoch 1000/1000 Cost: 0.000037


In [9]:
var = torch.FloatTensor([[4.0]])
pred_y = model(var)
print(pred_y)

tensor([[7.9879]], grad_fn=<AddmmBackward0>)


In [10]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9930]], requires_grad=True), Parameter containing:
tensor([0.0159], requires_grad=True)]


다중선형회귀

In [15]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [16]:
model = nn.Linear(3,1)

In [17]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1188,  0.2937,  0.0803]], requires_grad=True), Parameter containing:
tensor([-0.0707], requires_grad=True)]


In [18]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [19]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 22642.416016
Epoch  100/2000 Cost: 4.976951
Epoch  200/2000 Cost: 4.733481
Epoch  300/2000 Cost: 4.502824
Epoch  400/2000 Cost: 4.284275
Epoch  500/2000 Cost: 4.077209
Epoch  600/2000 Cost: 3.881021
Epoch  700/2000 Cost: 3.695124
Epoch  800/2000 Cost: 3.519025
Epoch  900/2000 Cost: 3.352130
Epoch 1000/2000 Cost: 3.194023
Epoch 1100/2000 Cost: 3.044178
Epoch 1200/2000 Cost: 2.902206
Epoch 1300/2000 Cost: 2.767665
Epoch 1400/2000 Cost: 2.640176
Epoch 1500/2000 Cost: 2.519374
Epoch 1600/2000 Cost: 2.404892
Epoch 1700/2000 Cost: 2.296402
Epoch 1800/2000 Cost: 2.193589
Epoch 1900/2000 Cost: 2.096157
Epoch 2000/2000 Cost: 2.003828


Class 로 모델 구현

In [20]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1,1)
  
  def forward(self,x):
    return self.linear(x)

#super() 로 인해 부모 클래스의 속성을 가지고 초기화됨

In [21]:
model = LinearRegressionModel()

In [22]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [24]:
optimizer = torch.optim.SGD(model.parameters(), lr= 0.01)

In [25]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.510777
Epoch  100/2000 Cost: 0.040541
Epoch  200/2000 Cost: 0.025052
Epoch  300/2000 Cost: 0.015480
Epoch  400/2000 Cost: 0.009566
Epoch  500/2000 Cost: 0.005911
Epoch  600/2000 Cost: 0.003653
Epoch  700/2000 Cost: 0.002257
Epoch  800/2000 Cost: 0.001395
Epoch  900/2000 Cost: 0.000862
Epoch 1000/2000 Cost: 0.000533
Epoch 1100/2000 Cost: 0.000329
Epoch 1200/2000 Cost: 0.000203
Epoch 1300/2000 Cost: 0.000126
Epoch 1400/2000 Cost: 0.000078
Epoch 1500/2000 Cost: 0.000048
Epoch 1600/2000 Cost: 0.000030
Epoch 1700/2000 Cost: 0.000018
Epoch 1800/2000 Cost: 0.000011
Epoch 1900/2000 Cost: 0.000007
Epoch 2000/2000 Cost: 0.000004
